memory_limit = 512M
upload_max_filesize = 128M
post_max_size = 128M
max_execution_time = 300
max_input_vars = 5000
date.timezone = Asia/Jakarta
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
opcache.enable=1
opcache.memory_consumption=256
opcache.max_accelerated_files=20000